### ISSUE TITLE
Microphone is always on

### ISSUE THREAD

**Issue by SilentHeII** [libretro/desmume#25] opened 2018-03-22 19:44 UTC
I've been trying to play through the DS port of Resident Evil 1 on Rebirth Mode. The touch controls can be emulated rather comfortably, however there is a section that requires you to perform mouth-to-mouth to Richard via blowing into the microphone. Now, this wouldn't be an issue, however there is no way to disable the microphone. I've tried disabling it in the quick menu options, and even tried the toggle hotkey. The only noticeable change is that instead of turning off, the toggle simply switches between internal and random sound samples.  

![0314 - resident evil - deadly silence usa -180321-210416](https://user-images.githubusercontent.com/29898818/37794276-11548d70-2ddf-11e8-8714-219608aa704c.png)

**Comment by bearoso** [comment] 2018-03-22 20:12
Make sure force microphone enable is off (that option needs to be removed). Then you hit the microphone key when you need it to make noise (there's no physical microphone support). It seems to work fine for me.

**Comment by bearoso** [comment] 2018-03-22 20:29
I've removed the force enable microphone option, since it doesn't make sense without physical microphone support, and reworded the options to make more sense of what they can actually do.

**Comment by SilentHeII** [comment] 2018-03-22 20:48
I understand that. However, the option IS disabled AND my laptop microphone as well.

**Comment by bearoso** [comment] 2018-03-22 23:25
Can you provide a save state just before that location and the CRC32 of the ROM image you're using? If so, I'll try to reproduce it.

**Comment by SilentHeII** [comment] 2018-03-23 05:58
I have this savestate for just before the sequence shows up.
https://my.mixtape.moe/bwktir.state1
CRC32: DE3E278C

**Comment by TheLocoBandito** [comment] 2018-03-23 14:43
I don't own Resident Evil for DS per se but I just want to give my comment on the situation since I own a couple of games with Microphone support.

Zelda Phantom Hourglass seems to be using Microphone all the time despite me pressing the Microphone button, the bars are always filled to the top and dosen't go down.

Zelda Spirit Tracks I'm not sure of, have to look again.

But on Mario and Luigi - Bowser's Inside Story the bars is normal, low and the Microphone button works as normal and when pressed the bars is rising to show that the Microphone is working.

**Comment by bearoso** [comment] 2018-03-23 20:27
Ok, apparently the DS doesn't use 0 as flat in its mic interpretation. It's 8-bit, so you'd presume that or 0x80, but both those are interpreted as noise. I tried 0x40, which seems to work with Resident Evil and let me get past the part SilentHell was stuck at, so I committed that. I don't know, maybe the mic level is actually 4-bit. I remember reading somewhere that the hardware actually interpolates 1-bit. If it breaks something else, reopen.

**Closed by bearoso** 2018-03-23 20:27 UTC

**Comment by TheLocoBandito** [comment] 2018-03-25 10:50
@bearoso 

Seems to work perfectly now with all the games I have that have microphone support.

Zelda Phantom Hourglass, the bars is normal and functions just like Mario and Luigi - Bowser's Inside Story now.

Zelda Spirit Tracks is the most perfect example, the bars is normal and with a gentle touch of the microphone button the bars is gently rising and with a hard press it goes straight to the top.

Good work mate!
